### ISSUE TITLE
Cannot compile on OS X 10.8.5

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/ferret#1]
I get this error message:
```
g++ -Wall -Wextra -g -IYAPB++/source -std=c++0x YAPB++/simple_graph/symmetry_detect.cc YAPB++/simple_graph/symmetry_parse.cc  YAPB++/simple_graph/gason/gason.cpp  YAPB++/simple_graph/simple_graph.cc YAPB++/simple_graph/simple_parser.cc  -DDEBUG_LEVEL=0 -O3  -I YAPB++/source -o symmetry_detect
YAPB++/simple_graph/symmetry_parse.cc:193:12: error: no matching constructor for initialization of 'ifstream'
      (aka 'basic_ifstream<char>')
  ifstream file(fileName);
           ^    ~~~~~~~~
/usr/include/c++/4.2.1/fstream:465:7: note: candidate constructor not viable: no known conversion from
      'string' (aka 'basic_string<char>') to 'const char *' for 1st argument
      basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
      ^
/usr/include/c++/4.2.1/bits/fstream.tcc:894:25: note: candidate constructor (the implicit copy constructor)
      not viable: no known conversion from 'string' (aka 'basic_string<char>') to
      'const std::basic_ifstream<char>' for 1st argument
  extern template class basic_ifstream<char>;
                        ^
/usr/include/c++/4.2.1/fstream:451:7: note: candidate constructor not viable: requires 0 arguments, but 1 was
      provided
      basic_ifstream() : __istream_type(), _M_filebuf()
      ^
YAPB++/simple_graph/symmetry_parse.cc:288:27: error: use of undeclared identifier 'move'
      permutations.insert(move(permutation));
                          ^
2 errors generated.
Makefile:39: recipe for target 'symmetry_detect' failed
make: *** [symmetry_detect] Error 1
```

I got it to work by manually editing the Makefile, adding `-stdlib=libc++` to MYCFLAGS and modifying BUILDSTUFF to use `-lc++` instead of `-lstdc++`.

**Comment by fingolfin** [comment]
In the meantime, I finally upgraded to OS X 10.11, and compiling ferret just works...
